site_name: Zen UV 4.4 for Blender
site_description: Zen UV for Blender Documentation
nav:
    - Getting Started:
        - Introduction: index.md
        - Learning Videos: youtube_videos.md
        - Upgrade Zen UV 3 to Zen UV 4 FAQ: zenuv3_to_zenuv4.md
        - Installation and Update: installation.md
        - User Interface: user_interface.md
    - Modules:
        - Advanced UV Maps: adv_uv-maps.md
        - Seam Groups: seam_groups.md
        - Unwrap: unwrap.md
        - Select: select.md
        - Transform: transform.md
        - Stack: stack.md
        - Texel Density: texel_density.md
        - UV Checker: checker.md
        - Pack: pack.md
        - Preferences: preferences.md
        - Transform Tool: transform_tool.md
        - Sticky UV Editor: sticky_uv_editor.md
        - Favourites: favourites.md
    - Trim Sheets:
        - trimsheet.md
        - Trim Sheet Management: trimsheet_creation.md
        - trimsheet_operators.md
        - trimsheet_hotspot.md
    - Additional:
        - Addon Preferences: addon_prefs.md
        - user_script.md
        - Help: help.md
        - FAQs: troubleshooting.md
        - Changelog: changelg.md
        - Credits: credits.md
        - Our Add-ons: our_addons.md
        - Recommended Add-ons: recommended_addons.md
docs_dir: mkdocs
site_dir: docs

theme:
    name: readthedocs
    navigation_depth: 8
    analytics:
        gtag: 'G-7XHJ910WF8'

markdown_extensions:
    - smarty
    - admonition
    - attr_list
    - toc:
        permalink: 

copyright: <p>Copyright &copy; 2024 <a href="https://zenmasters.team/">Zen Masters</a></p>
