site_name: Zen UV 5.4 for Blender
site_description: Zen UV for Blender Documentation
nav:
    - Getting Started:
        - Introduction: index.md
        - Learning Videos: youtube_videos.md
        - Installation and Update: installation.md
        - User Interface: user_interface.md
        - Tutorial:
            - Step-by-Step Guide Examples: tutorial.md
            - Emergency Light:
                - Emergency Light (EN): tutorial/emergency_light/emergency_light_eng.md
                - Emergency Light (UA): tutorial/emergency_light/emergency_light_ukr.md
                - Emergency Light (RU): tutorial/emergency_light/emergency_light_rus.md
    - Modules:
        - Advanced UV Maps: adv_uv-maps.md
        - Seam Groups: seam_groups.md
        - Unwrap:
            - Unwrap: unwrap.md
            - Zen Unwrap: unwrap/zen_unwrap.md
            - Auto Unwrap: unwrap/auto_unwrap.md
        - Select: select.md
        - Transform:
            - Overview: transform_sys/panels_and_description.md
            - Independent Transform Operators: transform_sys/independent_ops.md
            - Unified Transform System: transform_sys/unified_transform_sys.md
            - Advanced Transform: transform_sys/advanced_operators.md
        - Stack: stack.md
        - Texel Density: texel_density.md
        - UV Checker: checker.md
        - Pack: pack.md
        - Preferences: preferences.md
        - Transform Tool: transform_tool.md
        - Touch Tool: touch_tool.md
        - Sticky UV Editor: sticky_uv_editor.md
        - Favourites: favourites.md
    - Trim Sheets:
        - Trim Sheets: trimsheet.md
        - Trim Sheet Management: trimsheet_creation.md
        - Trimsheet Operators: trimsheet_operators.md
        - Hotspot Mapping: trimsheet_hotspot.md
    - Additional:
        - Addon Preferences: addon_prefs.md
        - User Script: user_script.md
        - Help: help.md
        - FAQs: troubleshooting.md
        - Changelog:
            - Summary: changelog.md
            - Version 5.4.0: changelog/release_note_5.4.0.md
            - Version 5.3.3: changelog/release_note_5.3.3.md
            - Version 5.3.2: changelog/release_note_5.3.2.md
            - Version 5.3.1: changelog/release_note_5.3.1.md
            - Version 5.3.0: changelog/release_note_5.3.0.md
            - Version 5.2.1: changelog/release_note_5.2.1.md
            - Version 5.2.0: changelog/release_note_5.2.0.md
            - Version 5.1.0: changelog/release_note_5.1.0.md
            - Version 5.0.3: changelog/release_note_5.0.3.md
            - Version 5.0.2: changelog/release_note_5.0.2.md
            - Version 5.0.1: changelog/release_note_5.0.1.md
            - Version 5.0.0: changelog/release_note_5.0.0.md
            - Version 4.5.4: changelog/release_note_4.5.4.md
            - Version 4.5.2: changelog/release_note_4.5.2.md
            - Version 4.5.1: changelog/release_note_4.5.1.md
            - Version 4.5.0: changelog/release_note_4.5.0.md
            - Version 4.4.2: changelog/release_note_4.4.2.md
            - Version 4.4.1: changelog/release_note_4.4.1.md
            - Version 4.4: changelog/release_note_4.4.0.md
            - Version 4.3: changelog/release_note_4.3.md
            - Version 4.2.1: changelog/release_note_4.2.1.md
            - Version 4.2: changelog/release_note_4.2.md
            - Version 4.1: changelog/release_note_4.1.md
            - Version 4.0.1: changelog/release_note_4.0.1.md
            - Version 4.0: changelog/release_note_4.0.md
            - Version 3.1.0.4: changelog/release_note_3.1.1.0.md
            - Version 3.1.0.2: changelog/release_note_3.1.0.2.md
            - Version 3.0.2: changelog/release_note_3.0.2.md
            - Version 3.0.1: changelog/release_note_3.0.1.md
            - Version 3.0: changelog/release_note_3.0.md
            - Version 2.2.3: changelog/release_note_2.2.3.md
            - Version 2.2.2: changelog/release_note_2.2.2.md
            - Version 2.2.1: changelog/release_note_2.2.1.md
            - Version 2.2: changelog/release_note_2.2.md
            - Version 2.1.3: changelog/release_note_2.1.3.md
            - Version 2.1 Stacks: changelog/release_note_2.1.md
            - Version 2.0 Transform: changelog/release_note_2.0.md
            - Version 1.92 Texel Density: changelog/release_note_1.92.md
            - Version 1.9 Texture Checker: changelog/release_note_1.9.md
            - Version 1.8: changelog/release_note_1.8.md
            - Version 1.7: changelog/release_note_1.7.md
        - Credits: credits.md
        - Our Add-ons: our_addons.md
        - Recommended Add-ons: recommended_addons.md
docs_dir: mkdocs
site_dir: docs

theme:
    name: readthedocs
    navigation_depth: 8
    analytics:
        gtag: 'G-7XHJ910WF8'

plugins:
   - glightbox
   - search

markdown_extensions:
    - smarty
    - admonition
    - attr_list
    - toc:
        permalink: 
extra_css:
  - extra.css

copyright: <p>Copyright &copy; 2024-2025 <a href="https://zenmasters.team/">Zen Masters</a></p>
